/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutionRouteImport } from './routes/institution'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as InstitutionIndexRouteImport } from './routes/institution.index'
import { Route as InstitutionDashboardRouteImport } from './routes/institution/dashboard'
import { Route as InstitutionPatientsRouteImport } from './routes/institution/patients'
import { Route as InstitutionReportsRouteImport } from './routes/institution/reports'
import { Route as InstitutionSettingsRouteImport } from './routes/institution/settings'
import { Route as InstitutionTeamRouteImport } from './routes/institution/team'
import { Route as InstitutionUploadRouteImport } from './routes/institution/upload'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientAppointmentsRouteImport } from './routes/patient/appointments'
import { Route as PatientCarePlanRouteImport } from './routes/patient/care-plan'
import { Route as PatientDashboardRouteImport } from './routes/patient/dashboard'
import { Route as PatientProfileRouteImport } from './routes/patient/profile'
import { Route as PatientReportsIndexRouteImport } from './routes/patient/reports/index'
import { Route as PatientReportsReportIdRouteImport } from './routes/patient/reports/$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionRoute = InstitutionRouteImport.update({
  id: '/institution',
  path: '/institution',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionIndexRoute = InstitutionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionDashboardRoute = InstitutionDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionPatientsRoute = InstitutionPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionReportsRoute = InstitutionReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionSettingsRoute = InstitutionSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionTeamRoute = InstitutionTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionUploadRoute = InstitutionUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => InstitutionRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCarePlanRoute = PatientCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsIndexRoute = PatientReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsReportIdRoute = PatientReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/institution/dashboard': typeof InstitutionDashboardRoute
  '/institution/patients': typeof InstitutionPatientsRoute
  '/institution/reports': typeof InstitutionReportsRoute
  '/institution/settings': typeof InstitutionSettingsRoute
  '/institution/team': typeof InstitutionTeamRoute
  '/institution/upload': typeof InstitutionUploadRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/care-plan': typeof PatientCarePlanRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/profile': typeof PatientProfileRoute
  '/institution/': typeof InstitutionIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/reports/$reportId': typeof PatientReportsReportIdRoute
  '/patient/reports/': typeof PatientReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/institution/dashboard': typeof InstitutionDashboardRoute
  '/institution/patients': typeof InstitutionPatientsRoute
  '/institution/reports': typeof InstitutionReportsRoute
  '/institution/settings': typeof InstitutionSettingsRoute
  '/institution/team': typeof InstitutionTeamRoute
  '/institution/upload': typeof InstitutionUploadRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/care-plan': typeof PatientCarePlanRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/profile': typeof PatientProfileRoute
  '/institution': typeof InstitutionIndexRoute
  '/patient': typeof PatientIndexRoute
  '/patient/reports/$reportId': typeof PatientReportsReportIdRoute
  '/patient/reports': typeof PatientReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/institution/dashboard': typeof InstitutionDashboardRoute
  '/institution/patients': typeof InstitutionPatientsRoute
  '/institution/reports': typeof InstitutionReportsRoute
  '/institution/settings': typeof InstitutionSettingsRoute
  '/institution/team': typeof InstitutionTeamRoute
  '/institution/upload': typeof InstitutionUploadRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/care-plan': typeof PatientCarePlanRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/profile': typeof PatientProfileRoute
  '/institution/': typeof InstitutionIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/reports/$reportId': typeof PatientReportsReportIdRoute
  '/patient/reports/': typeof PatientReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/institution'
    | '/patient'
    | '/institution/dashboard'
    | '/institution/patients'
    | '/institution/reports'
    | '/institution/settings'
    | '/institution/team'
    | '/institution/upload'
    | '/patient/appointments'
    | '/patient/care-plan'
    | '/patient/dashboard'
    | '/patient/profile'
    | '/institution/'
    | '/patient/'
    | '/patient/reports/$reportId'
    | '/patient/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/institution/dashboard'
    | '/institution/patients'
    | '/institution/reports'
    | '/institution/settings'
    | '/institution/team'
    | '/institution/upload'
    | '/patient/appointments'
    | '/patient/care-plan'
    | '/patient/dashboard'
    | '/patient/profile'
    | '/institution'
    | '/patient'
    | '/patient/reports/$reportId'
    | '/patient/reports'
  id:
    | '__root__'
    | '/'
    | '/institution'
    | '/patient'
    | '/institution/dashboard'
    | '/institution/patients'
    | '/institution/reports'
    | '/institution/settings'
    | '/institution/team'
    | '/institution/upload'
    | '/patient/appointments'
    | '/patient/care-plan'
    | '/patient/dashboard'
    | '/patient/profile'
    | '/institution/'
    | '/patient/'
    | '/patient/reports/$reportId'
    | '/patient/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstitutionRoute: typeof InstitutionRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution': {
      id: '/institution'
      path: '/institution'
      fullPath: '/institution'
      preLoaderRoute: typeof InstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution/': {
      id: '/institution/'
      path: '/'
      fullPath: '/institution/'
      preLoaderRoute: typeof InstitutionIndexRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/dashboard': {
      id: '/institution/dashboard'
      path: '/dashboard'
      fullPath: '/institution/dashboard'
      preLoaderRoute: typeof InstitutionDashboardRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/patients': {
      id: '/institution/patients'
      path: '/patients'
      fullPath: '/institution/patients'
      preLoaderRoute: typeof InstitutionPatientsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/reports': {
      id: '/institution/reports'
      path: '/reports'
      fullPath: '/institution/reports'
      preLoaderRoute: typeof InstitutionReportsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/settings': {
      id: '/institution/settings'
      path: '/settings'
      fullPath: '/institution/settings'
      preLoaderRoute: typeof InstitutionSettingsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/team': {
      id: '/institution/team'
      path: '/team'
      fullPath: '/institution/team'
      preLoaderRoute: typeof InstitutionTeamRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/upload': {
      id: '/institution/upload'
      path: '/upload'
      fullPath: '/institution/upload'
      preLoaderRoute: typeof InstitutionUploadRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/care-plan': {
      id: '/patient/care-plan'
      path: '/care-plan'
      fullPath: '/patient/care-plan'
      preLoaderRoute: typeof PatientCarePlanRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports/': {
      id: '/patient/reports/'
      path: '/reports'
      fullPath: '/patient/reports/'
      preLoaderRoute: typeof PatientReportsIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports/$reportId': {
      id: '/patient/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/patient/reports/$reportId'
      preLoaderRoute: typeof PatientReportsReportIdRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface InstitutionRouteChildren {
  InstitutionDashboardRoute: typeof InstitutionDashboardRoute
  InstitutionPatientsRoute: typeof InstitutionPatientsRoute
  InstitutionReportsRoute: typeof InstitutionReportsRoute
  InstitutionSettingsRoute: typeof InstitutionSettingsRoute
  InstitutionTeamRoute: typeof InstitutionTeamRoute
  InstitutionUploadRoute: typeof InstitutionUploadRoute
  InstitutionIndexRoute: typeof InstitutionIndexRoute
}

const InstitutionRouteChildren: InstitutionRouteChildren = {
  InstitutionDashboardRoute: InstitutionDashboardRoute,
  InstitutionPatientsRoute: InstitutionPatientsRoute,
  InstitutionReportsRoute: InstitutionReportsRoute,
  InstitutionSettingsRoute: InstitutionSettingsRoute,
  InstitutionTeamRoute: InstitutionTeamRoute,
  InstitutionUploadRoute: InstitutionUploadRoute,
  InstitutionIndexRoute: InstitutionIndexRoute,
}

const InstitutionRouteWithChildren = InstitutionRoute._addFileChildren(
  InstitutionRouteChildren,
)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientCarePlanRoute: typeof PatientCarePlanRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientReportsReportIdRoute: typeof PatientReportsReportIdRoute
  PatientReportsIndexRoute: typeof PatientReportsIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientCarePlanRoute: PatientCarePlanRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientReportsReportIdRoute: PatientReportsReportIdRoute,
  PatientReportsIndexRoute: PatientReportsIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstitutionRoute: InstitutionRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
